### ISSUE TITLE
set color on button

### ISSUE THREAD

**Issue by afriedma** [kevlatus/ngx-bottom-nav#395]
Hi @kevlatus,

Is it possible to set the color on the button, like primary or accent.

Can you suggest a workaround, if its not possible.

Thank you.

**Comment by kevlatus** [comment]
Hi @afriedma,

I was trying to implement the [Material Design Spec](https://material.io/components/bottom-navigation) as close as possible, which does not mention primary or accent variants on buttons.

But you can use those variants on the bottom nav itself: `<ngx-bottom-nav color="primary">`.

If this does not help, you may use the declarative API to style the buttons with your own CSS:
```html
<ngx-bottom-nav>
  <button ngx-bottom-nav label="Home" routerLink="/" exact="true">
    <mat-icon ngxBottomNavIcon>home</mat-icon>
  </button>
</ngx-bottom-nav>
```

Does any of those suggestions suit your requirements?

**Comment by afriedma** [comment]
Thank you, I will try the declarative approach.

Cheers, Alex

On Dec 17, 2020, at 9:22 AM, Kevin Latusinski <notifications@github.com> wrote:

﻿

Hi @afriedma<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fafriedma&data=04%7C01%7C%7Cf6f81c4e1ecb4a2a51d808d8a2971b67%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637438117196245697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oqS24cLfT7JXUm%2Fm3Lbi7OdYa5WNbX%2ByI2kUE53eqsM%3D&reserved=0>,

I was trying to implement the Material Design Spec<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaterial.io%2Fcomponents%2Fbottom-navigation&data=04%7C01%7C%7Cf6f81c4e1ecb4a2a51d808d8a2971b67%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637438117196255694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=8JvLz8%2B9wrWo84B%2FeqYhmKY52Xo7ummK2wDTdg%2Fuwh0%3D&reserved=0> as close as possible, which does not mention primary or accent variants on buttons.

But you can use those variants on the bottom nav itself: <ngx-bottom-nav color="primary">.

If this does not help, you may use the declarative API to style the buttons with your own CSS:

<ngx-bottom-nav>
  <button ngx-bottom-nav label="Home" routerLink="/" exact="true">
    <mat-icon ngxBottomNavIcon>home</mat-icon>
  </button>
</ngx-bottom-nav>

Does any of those suggestions suit your requirements?

**Comment by kevlatus** [comment]
great! Feel free to open a pull request, if your solution seems useful for other s as well
